import { Poppins } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Providers";
/* eslint eqeqeq: "off", curly: "error" */

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "San Ildefonso Market",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={poppins.className}>{children}</body>
      </html>
    </AuthProvider>
  );
}
